# Generated by Django 3.2.7 on 2021-09-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='Product',
        ),
    ]
