# Generated by Django 3.2.7 on 2021-09-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscriptions',
            field=models.BooleanField(default=False),
        ),
    ]
